add_executable (${PROJECT_PREFIX}${CURRENT_NAME} "${CPP_NAME}" ${HEADER_NAME})

set_target_properties(${PROJECT_PREFIX}${CURRENT_NAME} PROPERTIES FOLDER ${CURRENT_DIR})	
set_target_properties(${PROJECT_PREFIX}${CURRENT_NAME} PROPERTIES OUTPUT_NAME "${CURRENT_NAME}")	
set_target_properties(${PROJECT_PREFIX}${CURRENT_NAME} PROPERTIES PROJECT_LABEL "${CURRENT_NAME}")

target_link_libraries(${PROJECT_PREFIX}${CURRENT_NAME}
	${Boost_LIBRARIES}
	${CMAKE_THREAD_LIB_INIT})

target_include_directories(${PROJECT_PREFIX}${CURRENT_NAME}
	PRIVATE
	${Boost_INCLUDE_DIR})

install (TARGETS ${PROJECT_PREFIX}${CURRENT_NAME} DESTINATION bin/${CURRENT_DIR})