file(GLOB HEADER_NAME *.h *.hpp)

string(REPLACE "/" ";" CMAKE_CURRENT_SOURCE_DIR_LIST ${CMAKE_CURRENT_SOURCE_DIR})
list(REVERSE CMAKE_CURRENT_SOURCE_DIR_LIST)
list(GET CMAKE_CURRENT_SOURCE_DIR_LIST 0 CURRENT_DIR2)
list(GET CMAKE_CURRENT_SOURCE_DIR_LIST 1 CURRENT_DIR1)
set(CURRENT_DIR "${CURRENT_DIR1}/${CURRENT_DIR2}")
set(PROJECT_PREFIX "${CURRENT_DIR1}${CURRENT_DIR2}")

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin/${CURRENT_DIR})
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib/${CURRENT_DIR})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib/${CURRENT_DIR})